#server.port=8090
#
#server.servlet.context-path=/
#
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/springweb?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
#spring.datasource.username=ssafy
#spring.datasource.password=ssafy
#
#mybatis.config-location=classpath:/mybatis/mybatisConfig.xml

server:
  port: 8090
  servlet:
    context-path: /
 
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springweb?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    dbcp2:
      max-idle: 20
  servlet:
    multipart:
      max-file-size: 2000000
      
mybatis:
  config-location: classpath:/mybatis/mybatisConfig.xml